### ISSUE TITLE
Code cleanup on EV logging

### ISSUE THREAD

**Issue by rdviii** [sfc-aqua/quisp#118]
Everywhere that log messages are printed, at the moment, they all use `EV`.  That's the old style in OMNeT++.  These should all be upgraded to `EV_xxx`, as appropriate.  This will help us filter the messages better.
https://doc.omnetpp.org/omnetpp/manual/#sec:config-sim:logging
Related to #100.

**Comment by Chibikuri** [comment]
EV logging is changed to EV_DEBUG. They appear when we run it in the debug mode.
