### ISSUE TITLE
Impossible to find Kaami_master_quisp on Windows installer

### ISSUE THREAD

**Issue by pieeppe** [sfc-aqua/quisp#126]
Hello everyone,
please could you help me about this issue?

I can't download the quisp because i have a problem in section 3 of windows installer with the repo that I should clone in my omnett++ directory.
When I get the repo in the mingwenv nothing happens.

I'm following this installing guide:
https://github.com/sfc-aqua/quisp/blob/master/doc/Build_on_windows.md

I'd like to download the Kaami_master_quisp and for it i should have an username and a password to log in this file because in the repo there is a variable name to switch:
git clone https://<username>@bitbucket.org/sfc-aqua/kaaki_master_quisp.git

I've tried with the version that you can download in the github link, but it doesn't work.

![quisp](https://user-images.githubusercontent.com/64155310/80009965-0a57ae00-84ca-11ea-9f3f-8a51a62fd296.jpg)

Thank you in advance.

**Desktop (please complete the following information):**
 - OS: [Windows10 - build 1909]
 - QuISP version [I NEED IT PLEASE]
 - OMNeT++ version [5.6.1]

**Comment by Chibikuri** [comment]
Thank you for reporting.

This is an old version of the document. I'm sorry for confusing you. 
Please download this repository with
`git clone https://github.com/sfc-aqua/quisp.git`
or
Download from [here](https://github.com/sfc-aqua/quisp/releases).

The following process should be correct, but if you have problems again, feel free to ask us again.
Thank you.

**Comment by pieeppe** [comment]
Thank for your Anwering.
I've tried both link but doesn't still working.
For the link git clone https://github.com/sfc-aqua/quisp.git I found a problem in the properties, I can't set the eigen directory as in the image below: 
![Errore nelle propieta](https://user-images.githubusercontent.com/64155310/80125539-15761100-8592-11ea-978e-6e89ec400920.jpg)

While the other file give an error when you try to run a simulation as this in the image:
![Errore Quisp](https://user-images.githubusercontent.com/64155310/80125835-7d2c5c00-8592-11ea-993a-03ea61423936.jpg)

I followed the guide step by step, but i can't use the simulator.
Could you help me ?

thank you.

**Comment by Chibikuri** [comment]
Thank you for sharing.

Could you try clean project once?
<img width="1495" alt="Screen Shot 2020-04-24 at 14 12 56" src="https://user-images.githubusercontent.com/39610625/80177163-be297c80-8635-11ea-8db2-d90b74084c2e.png">
If the settings are correct, property screen should be like this.
<img width="866" alt="Screen Shot 2020-04-24 at 14 15 10" src="https://user-images.githubusercontent.com/39610625/80177225-08126280-8636-11ea-9ce5-51c4ec00b34f.png">

When you run a simulation, you have to choose .ini file in 
ex. quisp>quisp>network>quisp_tutorial.ini
<img width="404" alt="Screen Shot 2020-04-24 at 14 23 58" src="https://user-images.githubusercontent.com/39610625/80177650-43f9f780-8637-11ea-830a-250d4bbdd077.png">

If this solution doesn't help, please let me know.

Thank you

**Comment by pieeppe** [comment]
I've tried to clean the project and run the .ini file that you explain but still the same result, it doesn't work. It's the same error of before, like you can see in the image: 

![errore comune](https://user-images.githubusercontent.com/64155310/80208373-57ee2b00-8630-11ea-9c58-2ea65d0f8f2e.jpg)

I'm really sorry for all this problem, but I don't understand where the problem is.

**Comment by Chibikuri** [comment]
We're sorry for confusing you. 

Have you tried Makemake before you run the simulation?
<img width="865" alt="Screen Shot 2020-04-24 at 20 49 39" src="https://user-images.githubusercontent.com/39610625/80209501-2ba4cf80-866d-11ea-9798-dcac8e345773.png">

When you right-click "quisp" and click property, I think you can see this screen.
And then, please select "Options". (highlighted in the image)
<img width="865" alt="Screen Shot 2020-04-24 at 20 53 04" src="https://user-images.githubusercontent.com/39610625/80209835-b71e6080-866d-11ea-85ca-cf940cb26e6e.png">
I guess you can see a console like this.
<img width="1215" alt="Screen Shot 2020-04-24 at 20 54 44" src="https://user-images.githubusercontent.com/39610625/80209989-f187fd80-866d-11ea-8676-dbd6a44b443f.png">

To include eigen, we need to set the path to eigen in this makemake step.
<img width="1213" alt="Screen Shot 2020-04-24 at 20 57 17" src="https://user-images.githubusercontent.com/39610625/80210159-3c097a00-866e-11ea-8419-7e3a17d0a808.png">
 This path depends on your environment.

Hope this helps you!

Thank you.

**Comment by pieeppe** [comment]
Yes, I've done it. I'm looking at the guide for the operations and I set the Eigen library.

**Comment by Chibikuri** [comment]
If you try to run quisp itself, what will happen?
<img width="520" alt="Screen Shot 2020-04-25 at 12 31 44" src="https://user-images.githubusercontent.com/39610625/80270171-d6120680-86f0-11ea-9f06-6914d7131686.png">

**Comment by pieeppe** [comment]
When I click on run, after the processing, it gives me: 
![1](https://user-images.githubusercontent.com/64155310/80283796-b55ea680-871a-11ea-9553-c57ee4032fb0.jpg)
I click on OK and it gives me:
![2](https://user-images.githubusercontent.com/64155310/80283808-cb6c6700-871a-11ea-9555-d1844973ea31.jpg)
 after that, If I try to set an unconfigured network  and I choose 1 of the possible it gives me that error: 
![3](https://user-images.githubusercontent.com/64155310/80283857-2900b380-871b-11ea-858e-ef3242d00a73.jpg)

**Comment by rdviii** [comment]
Hi pieeppe, please check out the instructions on running the demo networks.
https://github.com/sfc-aqua/quisp/blob/master/doc/running-demos.md
You should come join the Slack, for faster turnaround on your questions. Give me or cocori (@Chibikuri)  an email address, and we will invite you.
Also, at this point, this thread has drifted a long ways from the original problem, so I'd like to close it. @Chibikuri is there anything in the more recent screenshots & questions that we should add to the documentation?

**Comment by Chibikuri** [comment]
It might be better to update some of the screenshots in 
https://github.com/sfc-aqua/quisp/blob/master/doc/Build_on_windows.md
It's better to put some links to the tutorials.

**Comment by pieeppe** [comment]
Thank you for your time, I will send my email to join the Slack.
