### ISSUE TITLE
Maybe Quisp could be made available for Python

### ISSUE THREAD

**Issue by ms286** [sfc-aqua/quisp#128]
I'm new at programming as I am a Physics student and not a computer science one. My current internship requires me to use QUISP but I am only familiar with Python.
Maybe this could be made available in Python as well.

**Comment by rdviii** [comment]
Hi, welcome to the QuISP community!
QuISP is tens of thousands of lines of code in C++, and it depends heavily on services provided by the OMNeT++ platform, so porting it to another language would probably be 6 to 12 months of pretty steady work.
We would _love_ to have the principles in QuISP replicated in other tools, both to confirm results we find and as we are working toward developing real-world protocols, so if you want to take on the task, we'll do our best to support your work.
Or, view this as an opportunity to learn C++ and join us in working directly on QuISP! There are lots of interesting tasks to be done, some of which can be done by relative beginners.  The coding in QuISP requires a fair amount of context, but is not inherently difficult. The single biggest hassle is getting it installed and running properly.
I'm also interested in where you are a student, and where you are doing an internship that is using QuISP!

**Comment by ms286** [comment]
Thank you for the welcome!
I understand it will be a huge task to make Quisp available in other languages. And yes, I would definitely take this as an opportunity to learn C++. I am currently a student at Université de Pierre et Marie Curie and I am working at LIP6.

**Comment by kenixer** [comment]
There's no need to reinvent the wheel. I think the implementation of a small Python interface for QuISP would be reasonable.
