### ISSUE TITLE
Ignoring .ini files in subdirectories in .gitignore?

### ISSUE THREAD

**Issue by rdviii** [sfc-aqua/quisp#130]
When I merged the new (well, sort of new) .gitignore file and did a git pull, I think I lost too many files:

delete mode 100644 quisp/networks/newNTimes/PerfectFixedChannelOnly10_nTimes_DS_DSinvPuri_Low_memEerr.ini
 delete mode 100644 quisp/networks/newNTimes/Perfect_FixedChannelOnly10_nTimes_DSXZinvPuri_Low_memErr_.ini
 delete mode 100644 quisp/networks/newNTimes/Perfect_FixedChannelOnly10_nTimes_XZPuri_Low_memErr_.ini
 delete mode 100644 quisp/networks/newNTimes/Perfect_FixedChannelOnly10_nTimes_XZinvPuri_Low_memErr_.ini
 delete mode 100644 quisp/networks/newNTimes/Perfect_FixedChannelOnly10_nTimes_separate_XXZPuri_Low_memErr.ini

So maybe the rule as written doesn’t correctly keep .ini files in subdirectories?

**Comment by zigen** [comment]
I think you have it. if not, you can find it here.
https://github.com/sfc-aqua/quisp/tree/0.1.0
https://github.com/sfc-aqua/quisp/tree/ee8873aa074b13687bcfaa703462d67811ab587b/quisp/networks/newNTimes
