### ISSUE TITLE
Cannot join the QuISP Slack channel

### ISSUE THREAD

**Issue by LesterKim** [sfc-aqua/quisp#146]
**Describe the bug**
Unclear instructions on joining the QuISP Slack group

**To Reproduce**
1. Try to [sign in to AQUA-QUISP](https://aqua-quisp.slack.com/). There is no mention of how to contact the workspace's administrator.
2. Click `Continue with Google`.
3. Choose Gmail account.
4. Got `Sorry, you entered an incorrect email address or password`.

**Expected behavior**
Sign in to the AQUA-QUISP workspace

**Screenshots**
![Screen Shot 2020-07-21 at 4 25 27 PM](https://user-images.githubusercontent.com/19293111/88103309-d2b2dd80-cb6e-11ea-97fb-f242a0d8d0c0.png)

**Desktop (please complete the following information):**
 - OS: Mac without Docker
 - QuISP version [current](https://github.com/sfc-aqua/quisp)

**Comment by LesterKim** [comment]
Also pointed out by @michelle4654

**Comment by kenixer** [comment]
In my opinion, you will need an invitation link from another Quisp Slack member to join.

**Comment by LesterKim** [comment]
I understand. Please let me know what steps to take after confirming with @rdviii.

**Comment by kenixer** [comment]
I just talked with @MakotoNakai . He will send you an invitation link sooner or later via email.

**Comment by MakotoNakai** [comment]
Hello Lester,  I'm dave and am a member of the QuISP developer team.
I sent the invitation link to the email address on your profile, and please confirm that you got an email from Slack.
( I might be supposed to ask your private email address, but I couldn't find any info about how to send DM on Github)

**Comment by LesterKim** [comment]
@MakotoNakai Thank you! Could you please add @michelle4654 and @wfinigan as well? Respectively, their emails are michelle@aliroquantum.com and will@aliroquantum.com.

**Comment by MakotoNakai** [comment]
Of course!  I sent them the invitation links!!

**Comment by LesterKim** [comment]
@MakotoNakai Could you add @mcubeddu (email: mcubeddu@aliroquantum.com) as well?

**Comment by rdviii** [comment]
So everyone here got an invite, except maybe mcubeddu?

Dave, can you finish and close this issue?

**Comment by MakotoNakai** [comment]
@LesterKim  Sorry for my late response.   I just invited that person.
