### ISSUE TITLE
Simulation stops when no the buffer qubits are there

### ISSUE THREAD

**Issue by Chibikuri** [sfc-aqua/quisp#187]
**Describe the bug**
Crash or unexpected behavior?
The simulation crash (stops) when the qubits in two quantum nodes are all occupied.

**To Reproduce**
1. `.ini` file name Could be any .ini file?
2. Network name '....'
3. Any parameter settings '....'
4. Any additional actions to cause the bug '...'
5. If it's deep in the simulation, timestamp/event #.
6. What we see (how you know it's a bug).

**Expected behavior**
The resources should be consumed in some way, or just holding it is also fine. 
But, need some modification for finishing it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac or Windows, indicate with or without Docker]
 - QuISP version [e.g. the github commit number or link]
 - OMNeT++ version [if relevant]
 - Eigen version [if relevant]
 - Compiler or other build info [if you think it's relevant]

**Additional context**

**Comment by Naphann** [comment]
Should be fixed via #486
