### ISSUE TITLE
add new jobs to CI flow: clang-format, clang-tidy, unit-test, module-test

### ISSUE THREAD

**Issue by zigen** [sfc-aqua/quisp#196]
**Is your feature request related to a problem? Please describe.**
I introduced #190 #193 but we don't have CI workflows for these tests. 
we should run the tests to make QuISP more robust.
these tasks help the developer to add new features or fix bugs.

**Describe the solution you'd like**
just run the tests in Travis CI.

now `quisp/QuantumChannel.cc` is not formatted, so when you fix CI flow, CI will fail.
could you also format the file in this issue?

**Comment by Chibikuri** [comment]
Add
- [ ] clang-format
- [ ] clang-tidy
- [ ] unit-test
- [ ] module-test

**Comment by Chibikuri** [comment]
- [ ] Format Quantum Channel

**Comment by zigen** [comment]
@Chibikuri could you put tasks on the PR, not issue?
