### ISSUE TITLE
Error tracking return wrong values

### ISSUE THREAD

**Issue by Naphann** [sfc-aqua/quisp#227]
As raised by @PorametPat 

https://github.com/sfc-aqua/quisp/blob/878278366b751af7fa428348d409c53f7331044a/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L317-L320

https://github.com/sfc-aqua/quisp/blob/878278366b751af7fa428348d409c53f7331044a/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L340-L343

These methods are very misleading. They should not be called `measure_X` or `measure_Z` since they output whether there are errors or not. It should be renamed to `hasXError` and `hasZError`. And also the return value is wrong. 

They currently output 
- `false` if there is a bit flip
- `true` if there is no flip error

but as used here 

https://github.com/sfc-aqua/quisp/blob/878278366b751af7fa428348d409c53f7331044a/quisp/rules/Action.cc#L105-L113

It checks for `false` to mean there are no bit flip. 

Unless I misunderstood the `par("God_ZError")` to mean the opposite this is a very serious bug.

**Comment by zigen** [comment]
I'll take this
