### ISSUE TITLE
Tomography count doesn't reach the expected number of tomography

### ISSUE THREAD

**Issue by Chibikuri** [sfc-aqua/quisp#284]
**Describe the bug**
In some network configs, the number of tomographies still doesn't reach out the target count. 
The reason could be the limit of simulation time but need investigation

```
EndNode1<-->QuantumChannel{cost=-1;distance=1km;fidelity=1;bellpair_per_sec=-1;tomography_time=-1;tomography_measurements=-1;actual_meas=939; GOD_clean_pair_total=939; GOD_X_pair_total=0; GOD_Y_pair_total=0; GOD_Z_pair_total=0;}<-->EndNode2; F=1; X=0; Z=0; Y=0
EndNode2<-->QuantumChannel{cost=-1;distance=1km;fidelity=1;bellpair_per_sec=-1;tomography_time=-1;tomography_measurements=-1;actual_meas=939; GOD_clean_pair_total=939; GOD_X_pair_total=0; GOD_Y_pair_total=0; GOD_Z_pair_total=0;}<-->EndNode1; F=1; X=0; Z=0; Y=0
```
**To Reproduce**
Working in a different branch. Let me add this part later

**Expected behavior**
Should reach expected number of tomography.

**Desktop (please complete the following information):**
 - OS:ubuntu on docker

**Additional context**

**Comment by Naphann** [comment]
I think this does not happen anymore unless the number of buffers are not enough to execute the RuleSet. I will close this for now. If we can reproduce it later then we can reopen it.
