### ISSUE TITLE
Improvement on OMNeT Message Casting

### ISSUE THREAD

**Issue by Naphann** [sfc-aqua/quisp#295]
Currently when a module receive a message, the `handleMessage(cMsg *m)` method checks for the type and cast it to the intended type before using. 

Although not much of a performance impact, we can can gain a small benefit from not double checking the type

example here 

https://github.com/sfc-aqua/quisp/blob/3f693ed4ae3f8f9378ed328f09a8105477717d55/quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc#L67-L68

we already call `dynamic_cast<type>` on the message, there is no need to use `check_and_cast` here. Using static cast like shown below is probably a better way to go

```c++
if (dynamic_cast<ConnectionSetupRequest *>(msg) != nullptr) { 
   ConnectionSetupRequest *req = static_cast<ConnectionSetupRequest *>(msg); 
```

or use dynamic cast once, check if it's not null and use it right away. (so no double casting) something like
```c++
auto *crm = dynamic_cast<ConnectionSetupRequest *> (msg);
if (crm != nullptr) {
  // do something with crm
}
```

**Comment by zigen** [comment]
or this might be clearer. 
```cpp
if (auto *crm = dynamic_cast<ConnectionSetupRequest *>(msg)) {
  // do something with crm
}
```

**Comment by Naphann** [comment]
That does look nicer! I forgot we can use this syntax in c++.
