### ISSUE TITLE
Measurement Error does not reflect the error parameter

### ISSUE THREAD

**Issue by Naphann** [sfc-aqua/quisp#337]
Currently, measurement error is modeled using Single Qubit Gate Error or in other words Pauli Error. Although modeling it this way using bit-flip error before perfect measurement is correct, the way the code applies is not straightforward and is misleading to the parameter set by the users. 

### The current model

Measurement error uses the same function as single qubit gate error, `ApplySingleQubitGateError` which requires to set the error of X, Y, Z separately. There are 2 kinds of parameters to be set
1. Error rate (1 param)
2. If error occurs what is the ratio between X, Y, Z to occur (3 params)

### Example of why the current approach is misleading:
Suppose we want to measure a qubit that currently has no error in Z-basis and we want the error probability to be 0.3. 

The expected behaviour would be with 0.7 probability it should come out as `no_X_error` and 0.3 as `has_X_error`. If we set the `MeasurementErrorRate = 0.3` and the X, Y, and Z error ratio to be 1:1:1, we would instead get `no_X_error` outcome with 0.8 probability and not 0.7! Because if we roll the dice and get `Z_error` then it happens to be that we introduce `Z` error to the qubit but not the changing the readout result.

To fix this, suppose we want the Measurement Error of all measurement bases X, Y, Z to be 0.3 then we need to set the `rate = 0.45` and the ratio to be `1:1:1` which would still only work for X and Z measurement but not Y!

## The fix

Instead of adding unitary error before measurement, perform a perfect measurement in the basis that we want and just do a random coin flip at the result. Example pseudo code

```python
def measure_X(qubit):
    result = 1 if has_Z_error else -1
    r = random_number()
    if r > MeasurementErrorRate:
        result = result * (-1)
    return result
```

If we want, we can have 3 independent parameters instead of 4 dependent ones, `Measurement_Error_Rate_X`, `Measurement_Error_Rate_Y`, and `Measurement_Error_Rate_Z`and this would stop the confusion.

**Comment by ngym** [comment]
This is also related to the simulation model of qubits.
Related to https://github.com/sfc-aqua/quisp/issues/343 and https://github.com/sfc-aqua/quisp/issues/342

I would think that the stabilizer notation simulator is better for this purpose (measurement outcomes ar erequired) than the pauli error simulator.

**Comment by Naphann** [comment]
@ngym Yes, the three issues are related. Personally I think that Pauli error simulation can still achieve what we want. Currently the semantics of the methods and qubit models are used incorrectly but we should be able to fix that. 

The measurement in this issue has a misleading name, it shouldn't be measure but rather extracting error. Its purpose is for calculating fidelity, reconstructing density matrices, and probably for error correcting protocols (which I think would be better as another method). The **actual measurement** for RuleSet purposes which gives two eigenvalues only need to propagate errors to neighbour qubits. 

Discussing about stabilizer or other model is okay with me but I think this should involve @rdviii @mhajdusek as well. Maybe @zigen and @Chibikuri regarding implementation as well
