### ISSUE TITLE
rename HoM -> HOM

### ISSUE THREAD

**Issue by zigen** [sfc-aqua/quisp#373]
**Is your feature request related to a problem? Please describe.**
the word "HoM" is wrong spelled.
"HOM" stands for Hong-Ou-Mandel which is the name of a two photons interference effect.
the middle "o" means the name of a physicist, so it should be "HOM" not "HoM"

**Describe the solution you'd like**
rename all "HoM" to "HOM"

originally reported by @ngym

**Comment by res6idue** [comment]
fixed in #433
