### ISSUE TITLE
clang-format and clang-tidy not found in Docker

### ISSUE THREAD

**Issue by Chibikuri** [sfc-aqua/quisp#374]
**Describe the bug**
When I rebuild the container, clang-tidy and clang-format don't work. 
```
make[1]: clang-format: Command not found
make[1]: *** [makefrag:40: format] Error 127
make[1]: Leaving directory '/root/quisp/quisp'
make: *** [Makefile:27: format] Error 2
```

**To Reproduce**
1. Build container with current docker image
2. run `make run-unit-test` (other command should also be fine)
3. run `make format`

**Additional context**
In the Dockerfile, it seems to be properly installed and linked.

**Comment by zigen** [comment]
hmm weird. it should be installed here https://github.com/sfc-aqua/quisp/blob/master/Dockerfile#L7-L8

**Comment by Chibikuri** [comment]
Yeah, it's installed
<img width="399" alt="Screen Shot 2022-02-04 at 14 43 20" src="https://user-images.githubusercontent.com/39610625/152478614-07ca5e4d-462b-4e8b-aca5-d9afd95d7c75.png">
but somehow it's not working. 
<img width="301" alt="Screen Shot 2022-02-04 at 14 43 33" src="https://user-images.githubusercontent.com/39610625/152478642-964b9810-77a7-462b-bf21-1a541e623009.png">
I'll try to re-link them.

**Comment by Chibikuri** [comment]
Oh, wait, clang-format-12 is not installed properly.

**Comment by Chibikuri** [comment]
Hmm, I'll try to rebuild container again.

**Comment by zigen** [comment]
we might need to bump llvm to 13 
https://releases.llvm.org/download.html

**Comment by Chibikuri** [comment]
Maybe?
I manually installed it and now it works though...
