### ISSUE TITLE
Cannot compile and install quisp from omnet++

### ISSUE THREAD

**Issue by AldoLamarre** [sfc-aqua/quisp#396]
**Describe the bug**
22:23:57 **** Incremental Build of configuration debug for project quisp ****
make MODE=debug all 
PKG_CONFIG_STATUS=0
MSGC: PhotonicQubit.msg
MSGC: messages/base_messages.msg
MSGC: messages/connection_setup_messages.msg
MSGC: messages/entanglement_swapping_messages.msg
MSGC: messages/HoM_ipc_messages.msg
MSGC: messages/link_generation_messages.msg
MSGC: messages/purification_messages.msg
MSGC: messages/QNode_ipc_messages.msg
MSGC: messages/tomography_messages.msg
backends/ErrorTracking/Backend.cc
backends/ErrorTracking/Qubit.cc
channels/QuantumChannel.cc
channels/QuantumChannel.cc:46:59: error: ‘result_t’ has not been declared
   46 |   virtual void processMessage(cMessage *msg, simtime_t t, result_t &result);
      |                                                           ^~~~~~~~
channels/QuantumChannel.cc:124:65: error: ‘result_t’ has not been declared
  124 | void QuantumChannel::processMessage(cMessage *msg, simtime_t t, result_t &result) {
      |                                                                 ^~~~~~~~
channels/QuantumChannel.cc: In member function ‘virtual void quisp::channels::QuantumChannel::processMessage(omnetpp::cMessage*, omnetpp::simtime_t, int&)’:
channels/QuantumChannel.cc:125:41: error: cannot convert ‘omnetpp::simtime_t’ {aka ‘omnetpp::SimTime’} to ‘const omnetpp::SendOptions&’
  125 |   cDatarateChannel::processMessage(msg, t, result);  // Call the original processMessage
      |                                         ^
      |                                         |
      |                                         omnetpp::simtime_t {aka omnetpp::SimTime}
In file included from /home/al/omnetpp-6.0/include/omnetpp.h:43,
                 from channels/QuantumChannel.cc:6:
/home/al/omnetpp-6.0/include/omnetpp/cdataratechannel.h:321:69: note:   initializing argument 2 of ‘virtual omnetpp::cChannel::Result omnetpp::cDatarateChannel::processMessage(omnetpp::cMessage*, const omnetpp::SendOptions&, omnetpp::simtime_t)’
  321 |     virtual Result processMessage(cMessage *msg, const SendOptions& options, simtime_t t) override;
      |                                                  ~~~~~~~~~~~~~~~~~~~^~~~~~~
make: *** [Makefile:210: out/gcc-debug//channels/QuantumChannel.o] Error 1
"make MODE=debug all" terminated with exit code 2. Build might be incomplete.

22:24:10 Build Failed. 4 errors, 0 warnings. (took 13s.389ms)

Error when building from omnetpp

**To Reproduce**
I followed the installation steps from the wiki. 
It cannot build  "result_t" has not been defined. 

**Desktop (please complete the following information):**
 - OS: linux mint
 - QuISP version master. 0.2.1 also doesn't build for different errors. 
 - OMNeT++ 6.0

**Comment by zigen** [comment]
Thanks for raising the issue.
Currently, QuISP needs to be compiled with OMNeT++ 5.7.
You can fix it by using OMNeT++5.7 (you can download it [here](https://omnetpp.org/download/old)).

We are upgrading QuISP for OMNeT++6 on [this PR](https://github.com/sfc-aqua/quisp/pull/394)

**Comment by zigen** [comment]
now the PR merged and this issue was resolved
