### ISSUE TITLE
Omnet++6.0.1 fails configure in M1 mac

### ISSUE THREAD

**Issue by res6idue** [sfc-aqua/quisp#422]
**Omnet++  6.0.1 crashes**

**To Reproduce**
1. Download omnet++ 6.0.1
2. Run source setenv 
3. Run ./configure

**Expected behaviour**
The code should run with no errors.

**Screenshots**

<img width="445" alt="Screenshot 2022-09-10 at 20 12 03" src="https://user-images.githubusercontent.com/98823464/189480654-c33b1fd5-ef9e-4029-8065-4c0073cffb91.png">

**Desktop**
 - OS: macOS 12.5.1, without docker, M1
 - QuISP version 0.2.1
 - OMNeT++ version 6.0.1
 - Compiler or other build info Apple clang version 13.1.6

**Additional context**
The error was caused because it tried to read Version as a C++ file.
It was fixed by adding `//` at the beginning of Version.

**Comment by zigen** [comment]
The VSCode devcontainer helps with this problem https://github.com/sfc-aqua/quisp/pull/439
