### ISSUE TITLE
QuISP doesn't build and gives error: String index out of range: 0

### ISSUE THREAD

**Issue by res6idue** [sfc-aqua/quisp#423]
**QuISP doesn't build and gives error `String index out of range: 0`**

**To Reproduce**
This is just a simplification of the quisp wiki for [Install OMNeT for MacOS](https://github.com/sfc-aqua/quisp/wiki/Install-OMNeT---for-MacOS) and [Building QuISP with OMNeT IDE](https://github.com/sfc-aqua/quisp/wiki/Building-QuISP-with-OMNeT-IDE)
1. Download OMNeT++6
2. Clone quisp
3. Go to quisp and open Version, adding `//` in the first line of the file
4. Go to omnetpp-6.0 and run `source setenv`, `./configure`, `make`
5. Run `omnetpp`
6. Choose `quisp/` as the working directory
7. Refuse to install samples and INET framework
8. Go to `File -> Import...`, and select the `General -> Existing Project into Workspace` wizard
9. Select the quisp folder as the root directory, and check the only project that appears 
10. Right-click `quisp` in the project explorer and click `property`
11. Select Makemake tab and configure quisp's build as makemake 
12. Error happens
13. Even if you ignore this error once, it will keep coming up every time you try to build

**Expected behaviour**
No exceptions should happen

**Screenshots**
<img width="484" alt="Screenshot 2022-09-10 at 20 52 32" src="https://user-images.githubusercontent.com/98823464/189482074-77454cfe-6e66-4ce5-a371-33e78371e70b.png">
<img width="919" alt="Screenshot 2022-09-10 at 20 40 54" src="https://user-images.githubusercontent.com/98823464/189482158-d49111cc-2136-465f-91fa-b9c74e40a8cf.png">

**Desktop (please complete the following information):**
- OS: macOS 12.5.1, without docker, M1
- QuISP version 0.2.1
- OMNeT++ version 6.0.1
- Compiler or other build info: Apple clang version 13.1.6

**Comment by Chibikuri** [comment]
This is the same as my build problem. I haven't solved this yet though. You could use docker version if you want.

**Comment by Chibikuri** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=418579

**Comment by res6idue** [comment]
Issue solved by
- Create a x86_64 homebrew instance
- `$ $PATH_TO_X86_64_HOMEBREW/brew install llvm@14`
- In the quisp root directory, check that llvm@14 for x86_64 exists in the path
- `$ make (-j8)`
- `$ omnetpp`

**Comment by Naphann** [comment]
@res6idue Is this issue still relevant? If it is already resolved, this should be marked as closed.

**Comment by res6idue** [comment]
I think this issue is resolved by using the dev container. I will close it.
