### ISSUE TITLE
docker_tools.sh is outdated

### ISSUE THREAD

**Issue by res6idue** [sfc-aqua/quisp#425]
**Describe the bug**
On running `sh docker_tools.sh`, the command fails to`brew cask install`
**To Reproduce**
Steps to reproduce the behaviour:
1. clone quisp
2. run `sh docker_tools.sh`

**Expected behaviour**
This error shouldn't happen

**Screenshots**
<img width="608" alt="Screenshot 2022-09-13 at 14 48 09" src="https://user-images.githubusercontent.com/98823464/189819599-0794ff72-b80e-4a0c-bd17-e2a15b68fe9a.png">

**Desktop :**
- OS: macOS 12.5.1, with docker, M1
- QuISP version 0.2.1
- OMNeT++ version 6.0.1
- Compiler or other build info: Apple clang version 13.1.6

**Additional context**
The error was caused because brew changed it's cask command into an option.
That is, `brew cask install` -> `brew install --cask`

**Comment by zigen** [comment]
@res6idue thank you for reporting the issue! could you fix it and send PR? You already knew how to fix it as you commented.

**Comment by res6idue** [comment]
#426
