### ISSUE TITLE
docker_build.sh doesn’t exist in quisp

### ISSUE THREAD

**Issue by res6idue** [sfc-aqua/quisp#427]
**Describe the bug**
docker_build.sh doesn’t exist in quisp/
but the descriptions exist in [wiki](https://github.com/sfc-aqua/quisp/wiki/User-Guide-Docker)  

**To Reproduce**
Steps to reproduce the behaviour:
1. clone quisp
2. run `sh docker_tools.sh`
3. run `sh docker_build.sh`

**Expected behaviour**
docker_build.sh should exist in quisp/

**Screenshots**

**Desktop :**
- OS: macOS 12.5.1, with docker, M1
- QuISP version 0.2.1
- OMNeT++ version 6.0.1
- Compiler or other build info: Apple clang version 13.1.6

**Comment by zigen** [comment]
now the docker_build.sh is no longer needed because of https://github.com/sfc-aqua/quisp/pull/397

**Comment by zigen** [comment]
@res6idue, could you help to fix it? I think you can edit our wiki.

**Comment by res6idue** [comment]
Edited wiki page
