### ISSUE TITLE
Unknown Parameter in Routing Daemon

### ISSUE THREAD

**Issue by Naphann** [sfc-aqua/quisp#434]
**Describe the bug**
Currently, routing daemon (RD) expects the parameter `Speed_of_light_in_fiber` to be read from channel of QNode modules. 

https://github.com/sfc-aqua/quisp/blob/733e45be0ce9edf10d8ca27cd01d5b40dba1f2c0/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L72

But some of the older created NED files, e.g., those used in quisp_tutorial.ini "Three_HoM_star" or "Tutorial_Big_Q_Network" defined their own channel inside the NED file and not properly using the channels defined in "channels.ned" as shown below

https://github.com/sfc-aqua/quisp/blob/733e45be0ce9edf10d8ca27cd01d5b40dba1f2c0/quisp/networks/topology_star_network.ned#L23-L47

When the network is defined like this there will be an error popup saying something along this line
```
(omnetpp::cDatarateChannel)Three_HoM_star.EndNode[0].port$o[0].channel: Unknown parameter 'Speed_of_light_in_fiber' 
-- in module (quisp::modules::RoutingDaemon) Three_HoM_star.EndNode[0].qrsa.rd (id=40), during network initialization
```

**Suggested Fix**

Find and change all network files such that they all use the `ClassicalChannel` and `QuantumChannel` defined in channels.ned

**Comment by res6idue** [comment]
Fixed in #438
