### ISSUE TITLE
Connection setup and reject messages should have unique identifier

### ISSUE THREAD

**Issue by Naphann** [sfc-aqua/quisp#435]
Currently, connection setup and reject messages only contain source and address and how many Bell pairs are required for the connection.

When the application is able to generate multiple request and not all of them are rejected, it will be impossible for the application to know which request got rejected and which got accepted. So the message should contain application ID or some kind of unique identifier to the connection message.

**suggested fix**:

Associate each application request with application id and put them inside the connection setup/reject message.

**Comment by MakotoNakai** [comment]
@Naphann san

Can I work on this one?

**Comment by Naphann** [comment]
Sure, I'll assign you to this issue.
