### ISSUE TITLE
Rename purification protocols

### ISSUE THREAD

**Issue by Naphann** [sfc-aqua/quisp#505]
As can be seen below, we use enum and string which uses abbreviations to refer to each purification protocol.

https://github.com/sfc-aqua/quisp/blob/3166d7e578af1267a5391ad9a7253530d12f3b40/quisp/rules/Action.h#L14-L42

If you are familiar with QuISP that, you would probably know what each of them means but this is not a good idea for people to look at the code and understand it at a glance (either with or without mention in the documents).

For string, we should use a full name while for enum it is debatable but still should convey more information. For example,

`DSDA_SECOND` doesn't really tell us much, while `Double_Selection_X_Single_Selection_Z` would be obvious that we perform 2 error purification in a single round where we do the double selection for X and single selection for Z and it is clear that we would need 4 qubits (2 for double selection + 1 for single selection + 1 to keep).

**Comment by lmpawan10** [comment]
Hello @Naphann, I would like to work on this if it is still available.
