### ISSUE TITLE
When clicking "Set Up an Unconfigured Network", simulator breaks

### ISSUE THREAD

**Issue by sitong1011** [sfc-aqua/quisp#56]
When clicking File-"Set Up an Unconfigured Network", the simulator terminates. https://camo.githubusercontent.com/5c3417410b6642d65321c9361669b9070392c5d8/68747470733a2f2f692e696d6775722e636f6d2f6364693334766b2e706e67

Error code:
Simulation terminated with exit code: 139
Working directory: /root/models/quisp/networks
Command line: ../quisp -m -n .. quisp_tutorial.ini

Environment variables:
PATH=/root/omnetpp/bin::/root/omnetpp/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH=/root/omnetpp/lib::
OMNETPP_IMAGE_PATH=/root/omnetpp/images

**Comment by Chibikuri** [comment]
Should be fixed now. Close this issue once and may open when it occurs again.
