### ISSUE TITLE
Too many branches

### ISSUE THREAD

**Issue by oradomskyi** [sfc-aqua/quisp#564]
Hello QuISP Team,

You are 23 contributors, but 130 branches, most of which, have long been merged.

For example, branch ['crispr'](https://github.com/sfc-aqua/quisp/tree/crispr) had the last update 3 years ago, and now some 1k commits behind the main.

From the Ops point of view, it would be desirable to keep the main repo as clean as possible, so non-developer users would not clone things they don't need.

In case of long and sophisticated developments, developers could work in the forks of the main repo, synchronizing when needed and creating the pool requests between repositories.

Let me know what you think,
Sasha

**Comment by Naphann** [comment]
@oradomskyi Thank you for the contribution!

I agree that we have too many inactive branches and the repo could really use a cleanup by archiving those branches.

I don't fully agree with your second point regarding too many branches or too many commits though. You are correct that a non-developer will not be interested or need full git history and would be beneficial to just clone with limited history via `--depth` command. This is of course adding some complexity to the user but we could add that in the README as this is quite common.

Your suggestions are useful and I really appreciate the input, and I think we may want to implement some of them in the future. Either via git-flow or a trunk-based model might be a better fit with us when we have the chance to clean up.
