### ISSUE TITLE
qDijkstra

### ISSUE THREAD

**Issue by rdviii** [sfc-aqua/quisp#65]
Write a short qDijkstra.md that points to our paper and discusses link cost.

**Comment by rdviii** [comment]
Ah, this actually already exists (I was looking in the wrong repo), but needs a pointer to the arXiv paper
https://arxiv.org/abs/1206.5655

**Comment by MakotoNakai** [comment]
I marked complete in the spread sheet but for some reasons forgot to move it to the GitHub.
I also added the link to the paper above, so please check my pull request.
