### ISSUE TITLE
_MM and dm files still not being completely ignored

### ISSUE THREAD

**Issue by rdviii** [sfc-aqua/quisp#68]
VanMetedneysMBP:doc rdv$ git status
On branch docs
Your branch is up to date with 'origin/docs'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	deleted-text-chunks.md
	"../quisp/networks/\"Example_run\""
	"../quisp/networks/\"Example_run\"_dm"
	../quisp/networks/Tomography_networks.Linear_One_MIM
	../quisp/networks/Tomography_networks.Linear_One_MIM_dm
	../quisp/networks/Tomography_networks.Linear_One_MM
	../quisp/networks/Tomography_networks.Linear_One_MM_dm

nothing added to commit but untracked files present (use "git add" to track)

**Comment by Chibikuri** [comment]
Should be fixed now.
